
x-common-env: &common_env
  DEBUG: "1"
  SECRET_KEY: "dev-secret-change-me"
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: /sockets
  POSTGRES_PORT: "5432"
  POSTGRES_DB: mydatabase
  POSTGRES_USER: mydatabaseuser
  POSTGRES_PASSWORD: mypassword
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_URL: "unix:///sockets/redis.sock"
  PAYMENT_PROCESSOR_URL_DEFAULT: "http://payment-processor-default:8080"
  PAYMENT_PROCESSOR_URL_FALLBACK: "http://payment-processor-fallback:8080"
  SUBSCRIBER_QUEUE_MAXSIZE: "1000"
  SCHEDULER_WORKERS: "3"

services:

  web1: &web
    build: .
    container_name: rinha-web-1
    environment:
      <<: *common_env
      APP_SOCKET_NAME: "web1.sock"
    volumes:
      - sockets:/sockets
    depends_on:
      db:
        condition: service_healthy
      rds:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "65M"
    networks:
      - rinha-net
      - payment-processor-net

  web2:
    <<: *web
    container_name: rinha-web-2
    environment:
      <<: *common_env
      APP_SOCKET_NAME: "web2.sock"

  scheduler:
    build: .
    container_name: rinha-scheduler
    command: python scheduler_service.py
    environment:
      <<: *common_env
      REDIS_SOCKET_PATH: "/sockets/redis.sock"
    depends_on:
      db:
        condition: service_healthy
      rds:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "130M"
    restart: always
    volumes:
      - sockets:/sockets
    networks:
      - rinha-net
      - payment-processor-net

  lb:
    image: nginx:alpine
    container_name: rinha-lb
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets:ro
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "15M"
    networks:
      - rinha-net

  db:
    image: postgres:16-alpine
    container_name: rinha-db
    user: root
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - ./db/conf/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./db/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - sockets:/var/run/postgresql
    healthcheck:
      test: [
        "CMD-SHELL", 
        "pg_isready -h /var/run/postgresql -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      ]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "55M"
    restart: always
    networks:
      - rinha-net

  rds:
    image: redis:7-alpine
    container_name: rinha-redis
    user: root
    volumes:
      - ./redis.conf:/etc/redis/redis.conf:ro
      - sockets:/sockets
    command: [
      "redis-server",
      "/etc/redis/redis.conf"
    ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10M"
    networks:
      - rinha-net

volumes:
  pgdata:
  sockets:

networks:
  rinha-net:
    driver: bridge
  payment-processor-net:
    name: payment-processor
    external: true
