version: "3.9"

services:
  web1: &web
    build: .
    container_name: rinha-web-1
    environment:
      DEBUG: "1"
      SECRET_KEY: "dev-secret-change-me"
      ALLOWED_HOSTS: "*"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      PAYMENT_PROCESSOR_URL_DEFAULT: "http://payment-processor:8080"
      PAYMENT_PROCESSOR_URL_FALLBACK: "http://payment-processor-fallback:8080"
      APP_SOCKET_NAME: "web1.sock"
    volumes:
      - sockets:/sockets
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "110M"
    networks:
      - rinha-net
      - payment-processor-net

  web2:
    <<: *web
    container_name: rinha-web-2
    environment:
      DEBUG: "1"
      SECRET_KEY: "dev-secret-change-me"
      ALLOWED_HOSTS: "*"
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      PAYMENT_PROCESSOR_URL_DEFAULT: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_URL_FALLBACK: "http://payment-processor-fallback:8080"
      APP_SOCKET_NAME: "web2.sock"

  lb:
    image: nginx:alpine
    container_name: rinha-lb
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "60M"
    networks:
      - rinha-net

  db:
    image: postgres:16-alpine
    container_name: rinha-db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: mydatabaseuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "60M"
    networks:
      - rinha-net

  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10M"
    networks:
      - rinha-net

volumes:
  pgdata:
  sockets:

networks:
  rinha-net:
    driver: bridge
  payment-processor-net:
    name: payment-processor
    external: true