[project]
name = "rinha-de-backend-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "django-ninja>=1.4.3",
    "httpx>=0.28.1",
    "huey>=2.5.3",
    "psycopg>=3.2.9",
]
